# _config.page.yml中的配置对所有自定义页面生效，比如“关于我”
widgets:
    # 个人信息组件
    # -
    #     type: profile
    #     position: right
        
    # 最新文章组件
    # -
    #     type: recent_posts
    #     position: left

    # 分类组件
    # -
    #     type: categories
    #     position: right

    # 标签组件
    # -
    #     type: tags
    #     position: right

    # 时间轴|归档组件
    # -
    #     type: archives
    #     position: right

    # 链接组件
    # -
    #     type: links
    #     position: right

    # 目录组件
    # -
    #     type: toc
    #     position: right

    # 订阅更新组件
    # -
    #     type: subscribe_email
    #     position: right

    # 广告组件
    # -
    #     type: adsense
    #     position: right
